╵                ~~~~~~~~~~~~~~~~~~~~
❯ Changes detected. Rebuilding...
✔ Changes detected. Rebuilding...
Application bundle generation failed. [0.177 seconds] - 2026-05-14T01:02:49.568Z

X [ERROR] TS2339: Property 'data' does not exist on type 'DetailCardComponent'. [plugin angular-compiler]
    libs/browser/shared/josanz-ui/src/lib/components/detail-card.html:20:13:
      20 │         @if (data && data[0]) {
         ╵              ~~~~
  Error occurs in the template of component DetailCardComponent.
    libs/browser/shared/josanz-ui/src/lib/components/detail-card.ts:8:15:
      8 │   templateUrl: './detail-card.html',
        ╵                ~~~~~~~~~~~~~~~~~~~~
X [ERROR] TS2339: Property 'data' does not exist on type 'DetailCardComponent'. [plugin angular-compiler]
    libs/browser/shared/josanz-ui/src/lib/components/detail-card.html:20:21:
      20 │         @if (data && data[0]) {
         ╵                      ~~~~
  Error occurs in the template of component DetailCardComponent.
    libs/browser/shared/josanz-ui/src/lib/components/detail-card.ts:8:15:
      8 │   templateUrl: './detail-card.html',
        ╵                ~~~~~~~~~~~~~~~~~~~~
X [ERROR] TS2339: Property 'data' does not exist on type 'DetailCardComponent'. [plugin angular-compiler]
    libs/browser/shared/josanz-ui/src/lib/components/detail-card.html:23:16:
      23 │              {{ data[0] }}
         ╵                 ~~~~
  Error occurs in the template of component DetailCardComponent.
    libs/browser/shared/josanz-ui/src/lib/components/detail-card.ts:8:15:
      8 │   templateUrl: './detail-card.html',
        ╵                ~~~~~~~~~~~~~~~~~~~~