✔ Building... Application bundle generation failed. [21.141 seconds] - 2026-04-04T10:09:46.600Z
X [ERROR] TS2339: Property 'validUntil' does not exist on type 'Budget'. [plugin angular-compiler]
    libs/browser/feature/budget/feature/src/lib/budget-detail/budget-detail.component.ts:103:42:
      103 │             [value]="formatDate(budget()?.validUntil)"
          ╵                                           ~~~~~~~~~~

Watch mode enabled. Watching for file changes...